

server:
  port: 8081

paths.auth:
  basePath: http://localhost:8080
  introspect: /api/introspectToken

security.clientId: 562ed6c2-86f8-4846-96b7-1dc1faf73fb6
security.clientSecret: ACiMy4L8gp/enQziGYb82rHrjHXtD0a+hLFazm5tpcY=

spring:
  main:
    web-application-type: REACTIVE
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
        - DedupeResponseHeader=Access-Control-Allow-Methods
        - DedupeResponseHeader=Access-Control-Allow-Headers
        - DedupeResponseHeader=Access-Control-Expose-Headers
        - DedupeResponseHeader=Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      httpclient:
        ssl:
          useInsecureTrustManager: true
        connect-timeout: 20000    # socket connection timeout
        pool:
          max-connections: 1500   # max allowed active connections
          type: FIXED             # fixed pool of max connections
          metrics: true           # routing httpclient metrics
      routes:
        #########################################
        #             OAUTH                     #
        #########################################
        - id: oauth-login
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/authorization/login
          filters:
            - RewritePath=/edge-service/v1/authorization/login, /api/login

        - id: oauth-refresh
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/authorization/refreshToken
          filters:
            - name: CustomHeaderFilter
              args:
                headerName: authorization
                headerValue: "Basic ${security.clientId}:${security.clientSecret}"
            - RewritePath=/edge-service/v1/authorization/refreshToken, /api/refreshToken

        - id: oauth-logout
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/authorization/logout
          filters:
            - name: CustomHeaderFilter
              args:
                headerName: authorization
                headerValue: "Basic ${security.clientId}:${security.clientSecret}"
            - RewritePath=/edge-service/v1/authorization/logout, /api/logout

        #########################################
        #         REQUIEREN FILTRO              #
        #########################################

        ##PRODUCTOS##
        - id: services-productos-consultar
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/service/productos/consultar
            # - Header=scope, httpbin
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Producto
                accion: Consultar
            - RewritePath=/edge-service/v1/service/productos/consultar, /api/producto/consultar

        - id: services-productos-crear
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/service/productos/crear
            # - Header=scope, httpbin
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Producto
                accion: Consultar
            - RewritePath=/edge-service/v1/service/productos/crear, /api/producto/crear

        - id: services-productos-actualizar
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/service/productos/actualizar/**
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Producto
                accion: Editar
            - RewritePath=/edge-service/v1/service/productos/actualizar/(?<idproductos>.*), /api/producto/actualizar/$\{idproductos}

        - id: services-productos-eliminar
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/service/productos/eliminar/**
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Producto
                accion: Eliminar
            - RewritePath=/edge-service/v1/service/productos/eliminar/(?<idproducto>.*), /api/producto/eliminar/$\{idproducto}


        - id: services-productos-agrupados-consultar
          uri: https://localhost:7084
          predicates:
            - Path=/edge-service/v1/service/productos/consultar/agrupados
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Producto
                accion: Consultar
            - RewritePath=/edge-service/v1/service/productos/consultar/agrupados, /api/Productos/Agrupados

        - id: services-productos-existencias-consultar
          uri: https://localhost:7084
          predicates:
            - Path=/edge-service/v1/service/productos/con/existencias
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Producto
                accion: Consultar
            - RewritePath=/edge-service/v1/service/productos/con/existencias, /api/Productos/productos-con-existencias


        ##CATEGORIAS##
        - id: services-categoria-consultar
          uri: https://localhost:7084
          predicates:
            - Path=/edge-service/v1/service/categorias/consultar
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Producto
                accion: Consultar
            - RewritePath=/edge-service/v1/service/categorias/consultar, /api/Categorias

        ##VENTAS##
        - id: services-venta-barra-crear
          uri: https://localhost:7084
          predicates:
            - Path=/edge-service/v1/service/venta/barra/crear
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Venta
                accion: Crear
            - RewritePath=/edge-service/v1/service/venta/barra/crear, /api/Ventas/Barra

        - id: services-venta-barra-notificacion
          uri: https://localhost:7084
          predicates:
            - Path=/edge-service/v1/service/venta/barra/crear/**
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Venta
                accion: Crear
            - RewritePath=/edge-service/v1/service/venta/barra/crear/(?<idventa>.*), /api/Ventas/Barra/$\{idventa}

        - id: services-venta-consultar
          uri: https://localhost:7084
          predicates:
            - Path=/edge-service/v1/service/venta/consultar/**
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Venta
                accion: Consultar
            - RewritePath=/edge-service/v1/service/venta/consultar/(?<idventa>.*), /api/Ventas/$\{idventa}

        - id: services-venta-mesa-crear
          uri: https://localhost:7084
          predicates:
            - Path=/edge-service/v1/service/venta/mesa/crear
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Venta
                accion: Crear
            - RewritePath=/edge-service/v1/service/venta/mesa/crear, /api/Ventas/Mesa

        - id: services-venta-pendientes-consultar
          uri: https://localhost:7084
          predicates:
            - Path=/edge-service/v1/service/venta/pendiente/consultar
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Venta
                accion: Consultar
            - RewritePath=/edge-service/v1/service/venta/pendiente/consultar, /api/Ventas/Pendientes

        - id: services-venta-ultimo-mes-consultar
          uri: https://localhost:7084
          predicates:
            - Path=/edge-service/v1/service/venta/ultimo-mes/consultar
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Venta
                accion: Consultar
            - RewritePath=/edge-service/v1/service/venta/ultimo-mes/consultar, /api/Ventas/ventas-ultimo-mes

        - id: services-venta-por-mes-consultar
          uri: https://localhost:7084
          predicates:
            - Path=/edge-service/v1/service/venta/por-mes/consultar
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Venta
                accion: Consultar
            - RewritePath=/edge-service/v1/service/venta/por-mes/consultar, /api/Ventas/ventas-por-mes


        ##COMPRAS##
        - id: services-compras-consultar
          uri: https://localhost:7084
          predicates:
            - Path=/edge-service/v1/service/compras/consultar
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Compras
                accion: Consultar
            - RewritePath=/edge-service/v1/service/compras/consultar, /api/Compras

        - id: services-compras-ultimo-mes-consultar
          uri: https://localhost:7084
          predicates:
            - Path=/edge-service/v1/service/compras/ultimo-mes/consultar
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Compra
                accion: Consultar
            - RewritePath=/edge-service/v1/service/compras/ultimo-mes/consultar, /api/Compra/compras-ultimo-mes

        - id: services-compras-por-mes-consultar
          uri: https://localhost:7084
          predicates:
            - Path=/edge-service/v1/service/compras/por-mes/consultar
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Compra
                accion: Consultar
            - RewritePath=/edge-service/v1/service/compras/por-mes/consultar, /api/Compra/compras-por-mes


        ##Creditos##
        - id: services-creditos-ultimo-mes-consultar
          uri: https://localhost:7084
          predicates:
            - Path=/edge-service/v1/service/creditos/ultimo-mes/consultar
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Venta
                accion: Consultar
            - RewritePath=/edge-service/v1/service/creditos/ultimo-mes/consultar, /api/Creditos/creditos-ultimo-mes


        ##ROLES Y PERMISOS##
        - id: services-roles-consultar
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/service/roles/consultar
            # - Header=scope, httpbin
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Configuracion
                accion: Consultar
            - RewritePath=/edge-service/v1/service/roles/consultar, /api/roles

        - id: services-roles-crear
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/service/roles/crear
            # - Header=scope, httpbin
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Configuracion
                accion: Crear
            - RewritePath=/edge-service/v1/service/roles/crear, /api/rol/crear

        - id: services-roles-actualizar
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/service/roles/actualizar/**
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Configuracion
                accion: Editar
            - RewritePath=/edge-service/v1/service/roles/actualizar/(?<idrol>.*), /api/rol/actualizar/$\{idrol}

        - id: services-roles-eliminar
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/service/roles/eliminar/**
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Configuracion
                accion: Eliminar
            - RewritePath=/edge-service/v1/service/roles/eliminar/(?<idrol>.*), /api/rol/eliminar/$\{idrol}

        - id: services-roles-configuracion
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/service/roles/configuracion/crear
            # - Header=scope, httpbin
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Configuracion
                accion: Crear
            - RewritePath=/edge-service/v1/service/roles/configuracion/crear, /api/configuracion/guardar

        - id: services-permisos-consultar
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/service/permisos/consultar
            # - Header=scope, httpbin
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Configuracion
                accion: Consultar
            - RewritePath=/edge-service/v1/service/permisos/consultar, /api/permisos

          ##Proveedor##
        - id: services-proveedor-crear
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/service/proveedor/crear
            # - Header=scope, httpbin
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Proveedor
                accion: Crear
            - RewritePath=/edge-service/v1/service/proveedor/crear, /api/proveedor/crear

        - id: services-proveedor-consultar
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/service/proveedor/consultar
            # - Header=scope, httpbin
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Proveedor
                accion: Consultar
            - RewritePath=/edge-service/v1/service/proveedor/consultar, /api/proveedorconsultar

        - id: services-proveedor-consultar-id
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/service/proveedor/consultar/id/**
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Proveedor
                accion: Consultar
            - RewritePath=/edge-service/v1/service/proveedor/consultar/id/(?<idproveedor>.*), /api/proveedorconsultar/$\{idproveedor}

        - id: services-proveedor-actualizar-id
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/service/proveedor/actualizar/id/**
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Proveedor
                accion: Editar
            - RewritePath=/edge-service/v1/service/proveedor/actualizar/id/(?<idproveedor>.*), /api/proveedor/actualizar/$\{idproveedor}


        - id: services-proveedor-eliminar-id
          uri: http://localhost:8080
          predicates:
            - Path=/edge-service/v1/service/proveedor/eliminar/id/**
          filters:
            - name: AuthenticationFilter
              args:
                modulo: Proveedor
                accion: Eliminar
            - RewritePath=/edge-service/v1/service/proveedor/eliminar/id/(?<idproveedor>.*), /api/proveedor/eliminar/$\{idproveedor}


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'gateway'


logging:
  level:
    web: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
