name: app - flutter
on:
#  pull_request:
#    branches: [ tatiana2 ]
#    paths:
#      - 'Backend/apigateway/**'
#      - '.github/workflows/api-gateway-java.yaml'
  push:
    branches: [ main ]
    paths:
      - 'Frontend/Mobile/login/**'
      - '.github/workflows/app-build-deploy.yaml'

jobs:
  flutter_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend/Mobile/login

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # flutter-version: '3.16.8'
      
      # Fetches proj dependencies from pub
      - name: Install dependencies
        run: flutter pub get
        # ^ If you want to use a specific version of flutter
      
      # Runs unit test
      - name: Run tests
        run: flutter test

  app-deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend/Mobile/login
    needs:
      - flutter_job
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # flutter-version: '3.16.8'
      
      # Fetches proj dependencies from pub
      - name: Install dependencies
        run: flutter pub get
        # ^ If you want to use a specific version of flutter

      - name: Build android apk
        run: flutter build apk --release --dart-define-from-file=env/local.json
