name: Desplegar a ECR contenedor de c#

on:
 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Build and Push to ECR public
      id: build-and-push
      uses: pahud/ecr-public-action@8cd826db40befb59b0cd0b60b22a7ba72d06a7f7
      with:
        dockerfile: .Backend/venta/Dockerfile
        context: .Backend/venta/
        tags: |
          public.ecr.aws/u8j8i3w5/$ECR_REPOSITORY:$IMAGE_TAG
          public.ecr.aws/u8j8i3w5/$ECR_REPOSITORY:$IMAGE_TAG

#    - name: Build, tag, and push image to Amazon ECR
#      env:
#        ECR_REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
#        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
#        REGISTRY_ALIAS: alias
#        IMAGE_TAG: latest
#      run: |
#        docker build -t public.ecr.aws/u8j8i3w5/$ECR_REPOSITORY:$IMAGE_TAG -f Backend/venta/Dockerfile Backend/venta/
#        docker push public.ecr.aws/u8j8i3w5/$ECR_REPOSITORY:$IMAGE_TAG