name: Subir Front a EC2

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'Frontend/WEB/**'
      - '.github/workflows/upload-front.yaml'
  push:
    branches: [ main ]
    paths:
      - 'Frontend/WEB/**'
      - '.github/workflows/upload-front.yaml'
jobs:
  build:
    
    name: Deploy front
    runs-on: ubuntu-latest
    environment: Production

   
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Replace token for configAmbientes
      uses: cschleiden/replace-tokens@v1.1
      with:
        tokenPrefix: '${'
        tokenSuffix: '}'
        files: '["Frontend/WEB/js/configAmbiente.js"]'
      env:
        DOMAIN-EC2: http://ec2-44-211-171-147.compute-1.amazonaws.com

    - name: 📂 Set working directory
      run: cat Frontend/WEB/js/configAmbiente.js

    - name: 📂 rsync Upload front
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: Frontend/WEB/*
        remote_path: /var/www/html/
        remote_host: ec2-44-211-171-147.compute-1.amazonaws.com
        remote_user: ubuntu
        remote_key: "${{ secrets.SSH_PRIVATE_KEY_EC2 }}"
