name: Subir Front a EC2

on:
  push:
    branches:
      - tatiana2

jobs:
  build:
    
    name: Build Image
    runs-on: ubuntu-latest
    environment: Production

   
    steps:

    - name: Check out code
      uses: actions/checkout@v3

#    - name: 📂 Set working directory
#      run: cd Frontend/WEB/

    - name: 📂 rsync Upload front
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: Frontend/WEB/*
        remote_path: /var/www/html/imperio/
        remote_host: 44.201.209.2
        remote_user: ubuntu
        remote_key: "${{ secrets.SSH_PRIVATE_KEY_EC2 }}"
